name: Dunolint Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  dunolint-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install dunolint
        uses: ./setup-dunolint
        with:
          dunolint-version: 0.0.20260103

      - name: Check dunolint version
        run: dunolint --version

      - name: Lint Check
        uses: ./lint-check
        with:
          workspace-root: ./test
